[package]
edition = "2018"
name = "lisa_player"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "1"
napi-derive = "1"
rodio = "0.14.0"
lazy_static = "1.4.0"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
